### PR TITLE
Add signal handling for SIGINT

### PR DESCRIPTION
**Pull request by GavinMendelGleason**

### CODE REVIEW

**Review by rrooij — APPROVED** [review]
Looks good! We might need to think about creating a cleanup job if there are things that should be saved before halting.

**Review by rrooij — CHANGES_REQUESTED** [review]
When testing this and running `terminusdb serve` and pressing Ctrl+C, I get the following error:

```
./terminusdb serve                                                                                                                                         signal_handler 1d ● ⬡
% Started server at http://localhost:6363/
% TerminusDB server started at Sunday, Sep 25, 20:44:32 CEST (utime 1664131472.9562778) args [serve,help(false),interactive(false),memory(_8906)]
% Welcome to TerminusDB's terminusdb-server, version 10.1.5!
% You can view your server in a browser at 'http://localhost:6363'

^CError: error(resource_error(stack),stack_overflow{choicepoints:10,depth:31,environments:23,globalused:50,localused:11,stack:[frame(31,system:call((:)/2),[]),frame(30,system:reset((:)/2,_190,_192),[]),frame(29,'$tabling':delim(ret/1,(:)/2,94475679990480,[]),[]),frame(28,'$tabling':activate(ret/1,(:)/2,94475679990480),[]),frame(27,'$tabling':run_leader(ret/1,(:)/2,fresh/2,_292,_294),[])],stack_limit:16201108,trailused:1})
```

This is regardless of the storage being used.

**Comment by GavinMendelGleason** [comment]
This change will not alter the behaviour in `-i` since this starts a toplevel which has its own signal handlers, but instead fixes the bug in trying to interupt in a shell. 

It does not, however, give me the same behaviour of a stack-overflow... curious how that happens.

**Comment by rrooij** [comment]
Perhaps it is my SWI Prolog version. I'm using v8.4.2.

**Comment by rrooij** [comment]
Same problem with SWI Prolog v8.4.3 unfortunately.

**Pull request closed without merging**
