### PR TITLE
Tests and error improvements for document query

### PR DESCRIPTION
**Pull request by spl**

### CODE REVIEW

**Comment by spl** [comment]
This is a work-in-progress branch to add integration tests for and improve error responses for document query.

**Comment by spl** [comment]
@matko Can you describe some tests to check for <https://github.com/terminusdb/terminusdb/pull/793>?

**Comment by spl** [comment]
> @matko Can you describe some tests to check for #793?

Responded to in https://github.com/terminusdb/terminusdb/pull/793#issuecomment-979778225

**Comment by spl** [comment]
This is ready for review.

**Review by GavinMendelGleason — APPROVED** [review]

**Pull request merged**
