### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by rrooij**
Add security policy

### CODE REVIEW

**Review by spl — DISMISSED** [review]
I made <https://github.com/terminusdb/terminusdb/pull/894> into this branch.

**Comment by rrooij** [comment]
Not needed anymore. Thanks @spl  :partying_face:

**Comment by matko** [comment]
Reopening cause it's unclear to me why it was closed in the first place. we don't want a security policy with regard to vuln reporting?

**Comment by rrooij** [comment]
My bad, thought it was merged into main already.

**Review by matko — APPROVED** [review]

**Pull request merged**
