### PR TITLE
Updated link to Diátaxis authoring framework

### PR DESCRIPTION
**Pull request by evildmp**
The documentation system now has a new home of its own at https://diataxis.fr/.

### CODE REVIEW

**Comment by luke-feeney** [comment]
that's great! fantastic system

**Comment by evildmp** [comment]
@luke-feeney Not sure what the test failures are, or if I can do anything about them.

**Comment by Cheukting** [comment]
Some builds failed, it seems that it is not directly caused by the changes in this pull request. @rrooij could you have a look?

**Comment by Cheukting** [comment]
@rrooij I have fixed the links, can I merge it?

**Pull request merged**
