### PR TITLE
Unit type fixes

### LINKED ISSUE #1016: Seshat - do not get suspected/ suspected_unknown choice when I view a document
**Describe the bug**
Seshat - do not get suspected/ suspected_unknown choice when I view a document.

**To Reproduce**
```
{
   "general_variables":{
      "alternative_names":[
         {
            "@type":"AlternativeNames",
            "suspected_unknown":[]
         },
         {
            "@type":"AlternativeNames",
            "unknown":[]
         }
      ],
      "@type":"GeneralVariables"
   }
}
```

When I view this polity, I get 

```
{
   "@id":"Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc",
   "@type":"Polity",
   "general_variables":{
      "@id":"Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc/general_variables/GeneralVariables/f262031fa31341fc10622c60b66e5d7164bc13e223e2c83358f36872b1a40fff",
      "@type":"GeneralVariables",
      "alternative_names":[
         {
            "@id":"Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc/general_variables/Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc/general_variables/GeneralVariables/f262031fa31341fc10622c60b66e5d7164bc13e223e2c83358f36872b1a40fff/alternative_names/AlternativeNames/839d4598f15816360b6bec2147825ccf5c3508be853fcd51d99f751c820cbd63",
            "@type":"AlternativeNames"
         },
         {
            "@id":"Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc/general_variables/Polity/ace0b976373c268df2bb01a8d497dbc851adce49619c48f6ba3cdcc1b655efbc/general_variables/GeneralVariables/f262031fa31341fc10622c60b66e5d7164bc13e223e2c83358f36872b1a40fff/alternative_names/AlternativeNames/eb7f53ade5c8743d4bd55a1d833dbc3f4ba2fa30d3f2850362abe96f3df2172a",
            "@type":"AlternativeNames"
         }
      ]
   }
}
```
**Expected behavior**
I was expecting to get suspected:[] or suspected_unknown:[]. So I can tell which option use had choosen to display in UI. As of now I am unable to understand what the user chose while creating the polity.

**Screenshots**
 Need to understand what the user chose while creating the polity, in order to display suspected/ suspected_unknown in select otions
image

### PR DESCRIPTION
**Pull request by matko**
Fixes #1016.

### CODE REVIEW

**Comment by matko** [comment]
Making this a draft while looking into why unit types cannot be added to particular types.

**Comment by matko** [comment]
Fixes #1028 and #1029 too.

**Comment by spl** [comment]
Can you add tests for these?

**Comment by matko** [comment]
> Can you add tests for these?

yeah working on it. discovering various related bugs as I do so too. this will remain draft until unit tests are done and bugs are fixed.

**Review by GavinMendelGleason — APPROVED** [review]

**Pull request merged**
